### PR TITLE
Nit-picking text modification

### PR DESCRIPTION
**Pull request by joergdeutschmann-i7**
Tiny text modification regarding the listing in the Validating Phase

### CODE REVIEW

**Comment by gorryfair** [comment]
Is this extra conditional statement needed? - The rule "Validating Phase (Check flight_size on entry)" already checks the flight_size, so is the check redundant?

**Comment by joergdeutschmann-i7** [comment]
This was intended to be in line with the table in the Appendix.

If the text is put 1:1 into code, one could end up with the following:
```
On entry to the Validating Phase:
if(flight_size <= PipeSize)
   {enter Normal; CWND=PipeSize}
CWND=flight_size
```
Although it obviously does not make sense to set the CWND twice.

I kind of like the `If (FS>PS) {CWND=FS} else {CWND=PS; enter Normal}` better, but that's more a personal preference.

I changed the order of both bullet points just to have the "default" expected behavior first.
Anyway, the order of bullet points should not matter, right?

**Comment by gorryfair** [comment]
See #59 for a possible alternative?

**Comment by joergdeutschmann-i7** [comment]
Fixed by #59

**Pull request closed without merging**
